### ISSUE TITLE
[ENHANCEMENT] Lexer improvements + bugfix

### ISSUE THREAD

**Issue by Ranastra** [I-Language-Development/I-language-rust#35]
- fixed line and column counting to start from zero, '\n' now checked before whitespace
- simplified lexer errors
- return value of lex function changed to include the position of tokens to be used for error handling

**Comment by ElBe-Plaq** [comment]
Looks pretty good. But please use one of the templates (https://github.com/I-Language-Development/I-language-rust/issues/new/choose) next time.
